### PR TITLE
Added Julia version for EKS

### PR DESCRIPTION
**Pull request by charleskawczynski**
Copied from #40

### CODE REVIEW

**Comment by agarbuno** [comment]
Got it. I believe almost all of the EKS update is already in the EKS.jl file. As soon as we are comfortable with the final version we can delete the python template and the bkp.jl file.

**Comment by charleskawczynski** [comment]
@agarbuno is `update_ensemble!` the same for EKI and EKS?

**Comment by charleskawczynski** [comment]
@agarbuno I think this is ready if you're fine with the changes. Let me know, and I can rebase

**Comment by agarbuno** [comment]
Sure. I´ll take a look. Thanks a lot @charleskawczynski ! I'll get back to you tomorrow with news on this.

**Comment by bielim** [comment]
Closing this PR; it has been superseded by #70 and #76.

**Pull request closed without merging**
