### PR TITLE
Clean up CalibrateEmulateSample

### PR DESCRIPTION
**Pull request by bielim**
This PR is a major clean-up (goal: code hygiene and reduction of the insanely long precompile times, i.e., addressing #65) -- the following changes were made:

(1) Deleted the modules `EKS.jl`, `GPR.jl`, `Histograms.jl`, `problems.jl`, and `spaces.jl`. These modules are not functional and not being developed anymore.

(2) Deleted `test/EKS`, `test/Histograms`, `test/GPR`,  `test/L96m`, as well as `examples/GPR` and `examples/L96`, because they are based on non-functional modules or (in the case of `L96`) because they don't seem to demonstrate any CES functionality.

(3) Deleted `test/Cloudy`, moved and renamed its content (`test/Cloudy/runtests.jl`) to `examples/Cloudy/Cloudy_example.jl`. The Cloudy "test" never was a proper test but rather an example, so it fits much better in the `examples` folder. The Cloudy notebook (`examples/Cloudy/calibrate_emulate_sample_Cloudy_demo.ipynb`) was deleted as it's basically just a more "eye-friendly" version of `Cloudy_example.jl`.

(4) Moved `GModel.jl` to `examples/Cloudy`.  This module shows what a forward model G that maps the parameters u to G(u) could look like, but it does so using Cloudy as an example, and for that reason I never liked the fact that this module was there with all the general-purpose code in the first place. As a result of (3) and (4), there is no more Cloudy dependency in the tests or core CES code.

(5) Generated separate `Project.toml` and `Manifest.toml` files for each example. With this setup, running the core CES code does not require to precompile packages that are only used in the examples (e.g., `DifferentialEquations.jl`) anymore.

(6) Removed unused packages from the main `Project.toml` file

Finally, I also changed the way the `ScikitLearn.jl` imports are handled in `GPEmulator.jl`. At least on my machine, this solves the problems with the seg faults that I mentioned in the discussion to PR #63.

### CODE REVIEW

**Comment by bielim** [comment]
@dburov190: I believe you are the creator of `L96` -- I can see that it is an implementation of the Lorenz 96 model, but I'm not sure if it demonstrates any CES functionality. If it does, please let me know, and I'll re-include it. If not, I'd suggest to find another place/repo for it, in the interest of keeping the CES repo as clean as possible.

**Comment by bielim** [comment]
@charleskawczynski: One issue I see with the current structure (separate `Project.toml` files for each example while keeping only the packages needed for core CES functionality in the main `Project.toml`) is that it is very easy to accidentally add some of the example dependencies back in to the main `Project.toml`: E.g., when I am in`CalibrateEmulateSample.jl/` and do `include("examples/Cloudy/Cloudy_example.jl")` (rather than running the example from within `examples/Cloudy`), it will automatically start to update the main `Project.toml` with the packages needed to run `Cloudy_example.jl`. Is there a way to keep this from happening?

**Comment by bielim** [comment]
bors try

**Comment by jakebolewski** [comment]
35 -> 13 minutes, nice!

**Comment by charleskawczynski** [comment]
@bielim looks like you figured out how to avoid this auto-project update problem. Please reach out if this is not the case!

**Pull request merged**
