### PR TITLE
Modular emulator interface

### PR DESCRIPTION
**Pull request by odunbar**
## Purpose
Reduces the current Emulator interface dependence of Gaussian Processes. Now the GP can be swapped for another statistical emulator. 
 
## In the PR
- [x] New general `Emulator` class. This handles all the data manipulation e.g. Normalization, Standardization, Decorrelation
- [x] General interface functions for Emulator, `optimize_hyperparameters!`, `predict`
- [x] New `MachineLearningTool` type, 
- [x] Moved the Gaussian Processes into a `GaussianProcess <: MachineLearningTool` class
- [x] Example (e.g. `plot_GP`) to demonstrate the new interface
- [x] Unit tests
- [x] New doc strings.

## Additional change
Seems to be ongoing issues with unit testing Julia 1.5.4, so I have updated the Manifest, Docs.yml and Test.yml to Julia 1.6.X
 
## Changes to user experience:

Ingredients: 
```julia
gppackage = GPJL()
pred_type = YType()
GPkernel = ...
iopairs = PairedDataContainer(x_data,y_data)
```

### Old interface

Set up a `GaussianProcessEmulator` object
```julia 
    gp = GaussianProcess(
         iopairs,
         gppackage;
         GPkernel=GPkernel, 
         obs_noise_cov=nothing, 
         normalized=false, 
         noise_learn=true, 
	 truncate_svd=1.0, 
         standardize=false,
         prediction_type=pred_type, 
         norm_factor=nothing)
 ```
Then predict with it.
```julia
μ, σ² = GaussianProcessEmulator.predict(gp, new_inputs)
```
It is short, but it inherently is stuck to the Gaussian process framework. It also hides e.g. the training away, and we may wish to have this more open. The script below is more general, separating out which parameters are related to data processing and which relate to the specific ML tool.

### New interface
Setup a `GaussianProcess<:MachineLearningTool` object
```julia
 gp = GaussianProcess(
       gppackage;
       kernel=GPkernel,
       noise_learn=true,
       prediction_type=pred_type) 
```
and then create the general emulator type using `gp`
```julia
    em = Emulator(
        gp,
        iopairs,
        obs_noise_cov=nothing,
        normalize_inputs=false,
        standardize_outputs=false,
        truncate_svd=1.0)
```
Train and predict
```julia
Emulators.optimize_hyperparameters!(em)
μ, σ² = Emulators.predict(em, new_inputs)
```
### Adding a new `MachineLearningTool`
Include a new file `NewTool.jl` at the top of `Emulator.jl`
In this file define:
1. `struct NewTool <: MachineLearningTool` with constructor `NewTool(...)` to hold ML parameters and models
2. `function build_models!(NewTool,iopairs)` to build and store ML models. Called in Emulator constructor
3. `function optimize_hyperparameters!(NewTool)`to train the stored ML models. Called by method of same name in Emulator
4. `function predict(NewTool,new_inputs)` to predict with stored ML models Called by method of same name in Emulator

### CODE REVIEW

**Review by bischtob — APPROVED** [review]
Looks good to me.

**Comment by tsj5** [comment]
Hi all, looking over the latest CI errors -- the [error message](https://buildkite.com/clima/calibrateemulatesample-ci/builds/52#bd74b272-eab7-49af-a6aa-95c55716065a) for this PR matches that discussed in issue #125, with a root cause of using a julia 1.6 Manifest with CI scripts that use julia 1.5. This PR updated 1.5 -> 1.6 in `.github/workflows`, but not in `.buildkite/pipeline.yml`.

**Comment by odunbar** [comment]
bors try

**Comment by odunbar** [comment]
bors try

**Comment by odunbar** [comment]
bors try

**Comment by tsj5** [comment]
Apologies for my confusion over which branch to add features to. As discussed with @odunbar :

1. PR #129 should be accepted, which will update the feature branch for this PR (`orad/emulator-interface`) with
   a. updates to the examples, to use the new Emulator interface introduced in this PR;
   b. fixes to the buildkite configuration that fix the errors encountered [above](https://github.com/CliMA/CalibrateEmulateSample.jl/pull/120#issuecomment-1018001476).
2. This should resolve all outstanding issues with this PR, which can then be accepted (merged into `master`).

**Comment by odunbar** [comment]
bors try

**Pull request merged**
