### PR TITLE
Run experiments on cluster on bors try / merge

### PR DESCRIPTION
**Pull request by jakebolewski**
Eventually we will build the documentation with the experiment output similar to what we currently do for ClimateMachine.jl

### CODE REVIEW

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try-

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by odunbar** [comment]
Today I learnt about buildkite! 

LGTM - can we also set up the `docs` pipeline in this PR too?

**Comment by jakebolewski** [comment]
Yes we can follow what we did here:  https://github.com/CliMA/ClimateMachine.jl/blob/master/.buildkite/docs-pipeline.yml

**Pull request closed without merging**
