### PR TITLE
add buildkite setup to build examples

### PR DESCRIPTION
**Pull request by jakebolewski**
Example build output: https://buildkite.com/clima/calibrateemulatesample-ci/builds/39

Right now it is not hooked up to bors (so passing example build is optional) but we can change that if desired.

### CODE REVIEW

**Comment by jakebolewski** [comment]
bors try

**Review by odunbar — APPROVED** [review]
LGTM - outputs are the same on my laptop.

Can you add to the wiki examples section something telling users what to add regarding these load paths, so that figures work on the online setup?
e.g lines such as
```Julia
prepend!(LOAD_PATH, [joinpath(@__DIR__, "..", "..")])
include(joinpath(@__DIR__, "..", "ci", "linkfig.jl"))
```

**Comment by jakebolewski** [comment]
the link figure bit is only for ci, it's basically a no-op if it doesn't detect the buildkite env to display figures in the logs.

the load path here just references the in tree version of whatever the working version of CalibrateEmulateSample is in the repo, so if you change CES and then re-run the examples you will see the examples reflect those in tree changes. 

The practical implication of this is you have to first build the CES project before running the examples: 

```
cd CalibrateEmulateSample.jl
julia --project -e 'using Pkg; Pkg.instantiate()'
#... possibly make changes...
julia --project=examples/Lorenz -e 'using Pkg; Pkg.instantiate()'
julia --project=examples/Lorenz  examples/Lorenz/Lorenz_example.jl
```

I can add these steps to the README

**Pull request merged**
